version: '3'

services:
  aws-lambda:
    build:
      context: .
      dockerfile: ./docker/aws/Dockerfile
    container_name: aws-lambda-api
    hostname: aws-lambda-api
    tty: true
    env_file: .env
    environment:
      LAMBDA_TASK_ROOT: $AWS_LAMBDA_TASK_ROOT
      LAMBDA_RUNTIME_DIR: $AWS_LAMBDA_RUNTIME_DIR
      ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    ports:
    - $API_PORT:8080

  aws-lambda-api:
    build:
      context: ./docker/api
    container_name: aws-lambda-api
    hostname: aws-lambda-api
    command: bash
    working_dir: /app
    tty: true
    env_file: .env
    volumes:
    - .:/app:delegated
    - home:/home/node

volumes:
  home:
